version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_alpine
    ports:
      - 80:80
    volumes:
      - ./www:/public_html
      - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nginxphp

  php:
    container_name: php7-server
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./www:/public_html
    depends_on:
      - database
    networks: 
      - nginxphp
  
  database:
    image: mysql:5.7
    container_name: php7-database
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - nginxphp

networks: 
  nginxphp:
    driver: bridge